# Generated by Django 2.2.4 on 2019-08-28 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Accreditation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('type', models.CharField(choices=[('Standard', 'Standard'), ('Advanced', 'Advanced')], default='Standard', max_length=8)),
                ('date', models.DateField()),
                ('uc_username', models.CharField(max_length=50)),
                ('wfdf_userid', models.IntegerField()),
                ('last_modified_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
