# Generated by Django 2.2.4 on 2019-08-30 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accreditation',
            name='date',
            field=models.DateField(blank=True, verbose_name='Accreditation Date'),
        ),
        migrations.AlterField(
            model_name='accreditation',
            name='uc_username',
            field=models.CharField(max_length=50, verbose_name='Ultimate Central username'),
        ),
        migrations.AlterField(
            model_name='accreditation',
            name='wfdf_userid',
            field=models.IntegerField(blank=True, verbose_name='WFDF user ID'),
        ),
    ]
