# Generated by Django 2.2.4 on 2019-09-07 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("tracker", "0003_auto_20190905_1528")]

    operations = [
        migrations.AlterField(
            model_name="accreditation",
            name="date",
            field=models.DateField(verbose_name="Accreditation Date"),
        ),
        migrations.AlterField(
            model_name="accreditation",
            name="wfdf_userid",
            field=models.IntegerField(
                unique=True, verbose_name="WFDF user ID"
            ),
        ),
    ]
